### ISSUE TITLE
Should Scoops have finished being written before autoplotter says its finished?

### ISSUE THREAD

**Issue by xgcell** [ohager/burst-autoplotter#11]
Not sure if this is an error but it looks wrong to me.  Each plot is at different percentages, almost never 100% before it starts a new plot.  After all plots were created, it said it was finished but left each plot at different percentages complete.  What would cause this? Is the text wrong or did it really not write all the nonces?
![auto-plotter](https://user-images.githubusercontent.com/25159423/34898896-4987274a-f7aa-11e7-97db-d1732a6fa325.JPG)

**Comment by ohager** [comment]
Actually, scooping is being completed normally. The fact, that _100%_ doesn't appear is due to the process communication. Autoplotter ist just a simple wrapper that calls [XPlotter](https://github.com/Blagodarenko/XPlotter), i.e. spawns it as a process. Autoplotter reads and parses _stdout_ from the spawned process and reformats that output. (Un)Fortunately on Windows the read frequency from that stream is quite low, such that not all output can be read. In case of scooping the _100%_ messages disappear, before being read. By the way, because of low read frequency the CPU workload using Autoplotter is much lower than using the XPlotter directly. Updating console on high frequency is surprisingly costly.

**Comment by ohager** [comment]
Closing as this is an implicit consequence of lower level stack - no bug!
