### ISSUE TITLE
autoplotter won't accept my numeric id

### ISSUE THREAD

**Issue by gary0318** [ohager/burst-autoplotter#27]
Murphy always gets me. every time. my numeric id is 18 digits long. 

autoplotter says, 
                      "> Use your *numeric* account ID (minimum 19 digits), dude!"

But, I'm using my legit numeric id.

Any advice?
Gary

**Comment by ohager** [comment]
Fuck. I had this issue once, when I limited to 20 chars. Obviously,  I need to fix the validator to accept also 18 digit ID. Sorry, for that inconvenience.  I'll provide an hotfix for that ASAP

**Comment by gary0318** [comment]
no prob. i went to the ui.js in appdata and changed it to 18 for the time. But, I'll update it when you make the fix.

Thanks,
Gary

**Comment by ohager** [comment]
@gary0318 fixed.... just released 0.2.2
Thx for reporting that issue; I really appreciate your feedback. jfyi: I'm close to release a complete new version (0.3) with an entirely new interface (still cli based)

preview:
![image](https://user-images.githubusercontent.com/3920663/36949360-d74fcb20-1fc5-11e8-8d79-a664b8bf2971.png)

**Comment by ohager** [comment]
@gary0318 One more thing...the instruction set detection might fail due to missing dll. So, the current version might always fallback to use SSE, which is considerably slower than AVX(2). To fix this locally, you need to use the `instructionset-checker.exe` from https://github.com/ohager/burst-autoplotter/tree/blessed-ui/exe  This build comes with static linked lib and has no dll dependency at all.
